version: '3.4'

services:
  meetingmanager-service-api:
    container_name: meetingmanager-api
    image: meetingmanagerapi
    build:
      context: .
      dockerfile: MeetingManager.Service.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5001:80'
    secrets:
       - MEETINGMANAGER
       - RABBITMQ_HOST_NAME
       - RABBITMQ_PASSWORD
       - RABBITMQ_USER_NAME
    networks:
      - mm-network    
    depends_on:
      - db
    logging:
      driver: json-file

  db:
    container_name: meetingmanager-db
    image: postgres
    networks:
      - mm-network    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=meetingmanager
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

secrets:
  MEETINGMANAGER:
    external: true
  RABBITMQ_HOST_NAME:
    external: true
  RABBITMQ_PASSWORD:
    external: true
  RABBITMQ_USER_NAME:
    external: true

networks:
  mm-network:
    external: true
volumes:
  data:
    driver: local